/**
 * Log Audit Types
 *
 * Types for tracking log coverage, detecting orphaned logs, and generating
 * audit reports. Used to analyze how well a canvas maps to actual system logs.
 *
 * @see docs/CANVAS_LOG_ASSOCIATION.md for full audit documentation
 */

import type { OtelResource } from './otel';

/**
 * Status of a node based on log activity
 *
 * - `active`: Node is receiving logs normally
 * - `silent`: Node is defined but receiving no logs (may indicate misconfiguration)
 * - `error-heavy`: Node has unusually high error rate
 */
export type NodeActivityStatus = 'active' | 'silent' | 'error-heavy';

/**
 * Activity record for a single node
 *
 * Tracks log counts and health status for audit reporting.
 */
export interface NodeActivity {
  /** Node identifier */
  nodeId: string;

  /** Total log count during audit period */
  logCount: number;

  /** Error log count (severity >= ERROR) */
  errorCount: number;

  /** Warning log count (severity == WARN) */
  warnCount: number;

  /** Timestamp of last received log (null if never seen) */
  lastSeen: number | null;

  /** Computed activity status */
  status: NodeActivityStatus;
}

/**
 * Suggested action for orphaned logs
 *
 * - `add-node`: Log appears legitimate, add a node to the canvas
 * - `fix-instrumentation`: Resource attributes look wrong, fix the source
 * - `remove`: Log appears to be test/debug artifact, should be removed
 * - `investigate`: Unable to determine, needs manual investigation
 */
export type OrphanSuggestedAction = 'add-node' | 'fix-instrumentation' | 'remove' | 'investigate';

/**
 * An orphaned log group
 *
 * Logs that matched the canvas scope but didn't match any node's
 * resourceMatch criteria. Grouped by resource signature.
 */
export interface OrphanedLog {
  /**
   * Resource attributes from the orphaned logs
   *
   * This is the "signature" used to group similar orphans.
   * Contains the key attributes that could be used for matching.
   */
  resource: OtelResource;

  /** Number of logs with this resource signature */
  count: number;

  /**
   * Sample log bodies for debugging
   *
   * Limited by audit config's maxSamplesPerOrphan setting.
   */
  samples: string[];

  /** First seen timestamp */
  firstSeen: number;

  /** Last seen timestamp */
  lastSeen: number;

  /**
   * Suggested action based on heuristics
   *
   * Determined by analyzing the resource attributes and log patterns.
   */
  suggestedAction: OrphanSuggestedAction;

  /**
   * Reason for the suggested action
   *
   * Human-readable explanation of why this action was suggested.
   */
  suggestedReason?: string;
}

/**
 * Type of audit recommendation
 *
 * - `add-node`: Add a new node to handle orphaned logs
 * - `remove-node`: Remove a node that's always silent
 * - `fix-match`: Update a node's resourceMatch criteria
 * - `check-instrumentation`: Verify OTEL instrumentation on source service
 */
export type AuditRecommendationType =
  | 'add-node'
  | 'remove-node'
  | 'fix-match'
  | 'check-instrumentation';

/**
 * Priority level for recommendations
 */
export type AuditRecommendationPriority = 'high' | 'medium' | 'low';

/**
 * Audit recommendation
 *
 * Actionable suggestion generated from audit analysis.
 */
export interface AuditRecommendation {
  /** Type of recommendation */
  type: AuditRecommendationType;

  /** Target node ID or resource signature */
  target: string;

  /** Human-readable reason for this recommendation */
  reason: string;

  /** Priority level */
  priority: AuditRecommendationPriority;

  /**
   * Suggested configuration snippet (if applicable)
   *
   * For `add-node` recommendations, this may contain a suggested
   * resourceMatch configuration.
   */
  suggestedConfig?: Record<string, unknown>;
}

/**
 * Complete audit report for a canvas
 *
 * Generated by the AuditCollector after analyzing log routing data.
 *
 * @example
 * ```typescript
 * const report: AuditReport = {
 *   canvasId: 'checkout-system',
 *   generatedAt: Date.now(),
 *   period: {
 *     start: Date.now() - 86400000,  // 24h ago
 *     end: Date.now()
 *   },
 *   summary: {
 *     totalLogs: 45231,
 *     mappedLogs: 42108,
 *     orphanedLogs: 3123,
 *     coveragePercent: 93.1
 *   },
 *   nodeActivity: [...],
 *   orphans: [...],
 *   recommendations: [...]
 * };
 * ```
 */
export interface AuditReport {
  /** Canvas ID this report is for */
  canvasId: string;

  /** When this report was generated */
  generatedAt: number;

  /** Time period covered by this report */
  period: {
    start: number;
    end: number;
  };

  /** Summary statistics */
  summary: {
    /** Total logs in scope during period */
    totalLogs: number;

    /** Logs successfully routed to a node */
    mappedLogs: number;

    /** Logs in scope but not matching any node */
    orphanedLogs: number;

    /** Coverage percentage (mappedLogs / totalLogs * 100) */
    coveragePercent: number;

    /** Number of out-of-scope logs (for reference) */
    outOfScopeLogs?: number;
  };

  /** Per-node activity breakdown */
  nodeActivity: NodeActivity[];

  /** Orphaned log groups (grouped by resource signature) */
  orphans: OrphanedLog[];

  /** Actionable recommendations */
  recommendations: AuditRecommendation[];

  /** Warnings generated during audit */
  warnings?: string[];
}

/**
 * Result of routing a single log
 *
 * Used for real-time routing decisions and audit tracking.
 */
export interface LogRoutingResult {
  /**
   * Routing outcome
   *
   * - `routed`: Log matched a node
   * - `orphaned`: Log in scope but no node match
   * - `out-of-scope`: Log doesn't match canvas scope
   */
  status: 'routed' | 'orphaned' | 'out-of-scope';

  /** Node ID the log was routed to (if status is 'routed') */
  nodeId?: string;

  /** Match specificity score (if status is 'routed') */
  score?: number;

  /** Resource signature (if status is 'orphaned') */
  resource?: OtelResource;

  /**
   * Matching strategy used
   *
   * - `resource`: Matched via resourceMatch
   * - `path`: Matched via sources (path-based)
   * - `explicit`: Matched via explicit annotation in log
   */
  matchedBy?: 'resource' | 'path' | 'explicit';
}

/**
 * Event emitted when a log is orphaned
 *
 * Can be subscribed to for real-time orphan monitoring.
 */
export interface OrphanEvent {
  /** Timestamp of the orphan */
  timestamp: number;

  /** Resource attributes of the orphaned log */
  resource: OtelResource;

  /** Log body (truncated if too long) */
  body: string;

  /** Canvas ID where orphan was detected */
  canvasId: string;
}

/**
 * Create a resource signature for grouping orphans
 *
 * Extracts key attributes that should be used for matching.
 * Two logs with the same signature are considered the same "type" of orphan.
 *
 * @param resource Full resource attributes
 * @returns Signature containing key matching attributes
 */
export function createResourceSignature(resource: OtelResource): OtelResource {
  // Extract key attributes that would typically be used for node matching
  const signatureKeys = [
    'service.name',
    'service.namespace',
    'deployment.environment',
    'db.system',
    'db.name',
    'k8s.deployment.name',
    'k8s.namespace.name',
    'messaging.system',
    'messaging.destination.name',
  ];

  const signature: OtelResource = {};

  for (const key of signatureKeys) {
    if (resource[key] !== undefined) {
      signature[key] = resource[key];
    }
  }

  return signature;
}

/**
 * Convert a resource signature to a string key for Map/Set usage
 */
export function signatureToKey(resource: OtelResource): string {
  const entries = Object.entries(resource)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => a.localeCompare(b));

  return entries.map(([k, v]) => `${k}=${v}`).join('|');
}
